[env:heltec_v3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
extra_scripts = pre:tools/load_build_config.py

; NOTE: Adjust lib_deps as needed for your environment
lib_deps =
  https://github.com/meshtastic/Meshtastic-arduino.git#v0.0.7
  heltecautomation/Heltec ESP32 Dev-Boards
  mikalhart/TinyGPSPlus
  knolleary/PubSubClient

build_flags =
  -D CORE_DEBUG_LEVEL=0
  -D WIFI_LORA_32_V3
  -D HELTEC_BOARD=30
  -D SLOW_CLK_TPYE=0
  -D LoRaWAN_DEBUG_LEVEL=0

[env:heltec_v3_ci]
extends = env:heltec_v3
build_flags =
  ${env:heltec_v3.build_flags}
  -D ALLOW_PLACEHOLDER_SECRET
